version: '3.8'

services:
  school-notes-postgresql:
    image: postgres:last
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schoolnotes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata: /var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - school-notes-postgresql
    volumes:
      - pgadmin-data: /var/lib/pgadmin


volumes:
  pgdata:
  pgadmin-data: